### ISSUE TITLE
Gulp does not correctly track errors from plugin

### ISSUE THREAD

**Issue by vsenko** [cedx/david.gulp#5]
I configured the following task:
```javascript
gulp.task('david', () => {
  return gulp.src(`${__dirname}/package.json`)
    .pipe(david({
      error404: true,
      errorDepCount: 1,
      errorDepType: true,
      errorSCM: true,
      ignore: [],
      unstable: false,
      update: false,
    }))
    .pipe(david.reporter);
});
```
and  default task depends on task `david` and task `nsp`.

When I run gulp with outdated dependencies I see the following output:
```
[11:43:03] Starting 'nsp'...
[11:43:03] Starting 'david'...
[11:43:07] (+) No known vulnerabilities found
[11:43:07] Finished 'nsp' after 3.71 s
```
As you see, there is no error output from `gulp-david`.

If I have a vulnerable dependency `nsp` produces the following output:
```
[11:21:24] Starting 'nsp'...
[11:21:24] Starting 'david'...
[11:21:27] 'nsp' errored after 2.77 s
[11:21:27] Error in plugin 'gulp-nsp'
Message:
    (+) 1 vulnerabilities found
```

So it seems to me that errors from `gulp-david` are not recognized by gulp.

**Comment by cedx** [comment]
I will check it as soon as possible: probably the next week-end as I've haven't enough time during work days.

**Comment by vsenko** [comment]
The workaround for the problem is provided here: https://github.com/gulpjs/gulp/issues/71

```javascript
var origSrc = gulp.src;
gulp.src = function () {
    return fixPipe(origSrc.apply(this, arguments));
};
function fixPipe(stream) {
  var origPipe = stream.pipe;
  stream.pipe = function (dest) {
    arguments[0] = dest.on('error', function (error) {
      var nextStreams = dest._nextStreams;
      if (nextStreams) {
        nextStreams.forEach(function (nextStream) {
          nextStream.emit('error', error);
        });
      } else if (dest.listeners('error').length === 1) {
        throw error;
      }
    });
    var nextStream = fixPipe(origPipe.apply(this, arguments));
    (this._nextStreams || (this._nextStreams = [])).push(nextStream);
    return nextStream;
  };
  return stream;
}
```

And the task now looks like this:
```javascript
gulp.task('david', () => {
  return gulp.src(`${__dirname}/package.json`)
    .pipe(david({
      error404: true,
      errorDepCount: 1,
      errorDepType: true,
      errorSCM: true,
      ignore: [],
      unstable: false,
      update: false,
    }))
    .pipe(david.reporter)
    .on('error', (err) => {
      console.log('task david error:', err);
    })
    .on('end', () => { });
});
```

The output now looks like this:
```
[14:24:13] Starting 'david'...
task david error: [Error: [gulp-david] 1 outdated dependencies]
[14:24:15] 'david' errored after 2.42 s
[14:24:15] Error: [gulp-david] 1 outdated dependencies
```

As you can see the error is cached, but the report is never generated. And it it very sad.

I'm not too skilled in gulp plug-in development, but it seems like you could use **through2** wrapper as it is recommended in the guidelines: https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md#what-does-a-good-plugin-look-like
And throw errors using **PluginError** from **gulp-util**.

**Comment by cedx** [comment]
I've tested on my own side. An extract from my sample `gulpfile.js`:
```javascript
gulp.task('check', () => gulp.src('package.json')
  .pipe(plugins.david())
  .pipe(plugins.david.reporter)
);
```

When I run it with some outdated dependencies :
```shell
$ gulp check
[13:37:55] Using gulpfile /repo/reverse-proxy.js/gulpfile.js
[13:37:55] Starting 'check'...
/repo/reverse-proxy.js/package.json
devDependencies
  del { required: ^1.1.0, stable: 2.2.0, latest: 2.2.0 }
  gulp { required: ^2.9.0, stable: 3.9.0, latest: 3.9.0 }
[13:37:57] Finished 'check' after 2.88 s
```

The display is good. So the problem is more related to the way you pipe the plugins. Some plugins can't be used together due to the way they transform the input.

Concerning the errors that should be raised by the plugin: I think you misunderstood the way Gulp errors are handled (because of a flaw design in Node.js streams).
The Gulp guidelines say:
> Do not throw errors inside a stream.
> Instead, you should emit it as an error event.

That is exactly what my plugin does: it emits an error event when an issue is encountered.
From the guidelines:
> Your plugin should only do one thing, and do it well.

So, it's up to you to respond to this event. It's not the plugin role.

Other remarks:
- the `PluginError` class is intended for the formatting of error messages, not for error handling. I already use the recommended output.
- the `through2` module is intended to ease the use of Node.js streams. I already use plain streams.

You should really look at other Gulp plugins (like `gulp-less` for example) : they also handle errors by emitting an event.

**Comment by vsenko** [comment]
Can I ask you to take a closer look at my Gulp config? The difference between our tests is in the way we configure plug-in to act in case of outdated dependencies:
>    .pipe(david({
>      error404: true,
>      **errorDepCount: 1,**
>      errorDepType: true,
>      errorSCM: true,
>      ignore: [],
>      unstable: false,
>      update: false,
>    }))

I want the plug-in to throw an error in case of an outdated dependency and to break the build. While you print the report and continue.

Could you please test with `errorDepCount: 1`. The plug-in will throw an error but Gulp will not see it and continue. When other plug-ins fail Gulp stops processing tasks and fails too.

**Comment by cedx** [comment]
Let's try again :) The new `gulpfile.js` sample (using a `package.json` with 3 outdated dependencies):
```javascript
gulp.task('check', () => gulp.src('package.json')
  .pipe(david({ errorDepCount: 1 }))
  .on('error', error => {
    console.log(error);
    throw error; // You can also use (the result will be the same): process.exit(1);
  })
  .pipe(david.reporter)
);
```

And the new output:
```shell
$ gulp check
[20:36:54] Using gulpfile /repo/reverse-proxy.js/gulpfile.js
[20:36:54] Starting 'check'...
[Error: [gulp-david] 3 outdated dependencies]
```

As I stated above, there is some flaw design in Node.js streams. When an error event is emited, the next handlers in the pipe can't do their job correctly. In this case, the reporter can't print the list of outdated dependencies as the stream is already broken.

Maybe I should use a more detailled error message in the checker.

**Comment by vsenko** [comment]
Yep, as far as I understand, `david.reporter` becomes useless in case of `errorDepCount: 1`.

**Comment by cedx** [comment]
Unfortunately :( I wanted to keep the reporter separated from the checker in order to let the users decide by themselves what to do in case of outdated dependencies. But your issue confirm that it was not a good choice finally.

So I think that the checker and the reporter should be merged: I will do it in the next release, but I haven't enough time for the moment.
I'm completely open to external contributions: if you think you can do it, don't hesitate to submit a pull request.

**Comment by cedx** [comment]
The last release should please you:

```javascript
// `reporter` option is `true` by default, so it can be omitted.
gulp.task('check', () => gulp.src('package.json')
  .pipe(david({ errorDepCount: 1, reporter: true }))
  .on('error', err => throw err)
);
```

**Comment by vsenko** [comment]
This one is really useful! Thank you!
:+1:
